#$schema: https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: denis-project-frontend
  annotations:
    github.com/project-slug: djajcevic/denis-project-frontend-acs
    backstage.io/environment: dev
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=denis-project-frontend'
  tags:
    - react
    - js
spec:
  type: website
  lifecycle: development
  owner: demo-team
  system: demo
  dependsOn:
    - component:default/denis-project